---
language: python
python:
  - "3.5"

env:
  global:
    - secure: "aylndjBHlCj1s7WltItgjLOqf2HsEibo1k78IX7iXS8Dgld1AKI73g1926sJHI2NsEXqe0BC8eW3GxSUCAtBPsKNPur6OgkBY8GxLVdfMkZcU//N/oDChfro5jgOXIDKrKqgVZ5mFvtRwqfdDkKc7K2Pa520Wz1EXV86/7Br2B2E3iYnOAvlnonkThTrM+OathuuNYVeMMUW5GF8ns2T/HkuCnQyTtUwVIzw4DaRGh3jo4/QqKS80J/CmyJMOSr3T49TjhqGYFPTE8WEtEIZUim8XNV7PpdIPaJwlBgwCwuu+HZRCI3YHZeH+tLCFefper4lB63HqR+G37VoVVrOLMgkVwya6c3U7Y44/92l0aNoIWzyockhxr0f4wMRMWCu4QdIjwCIAs11oYm36YZKdbGqhxxdcYPzYlVzjwTfwOQscaOcvpDtBjxscsDmKampj30xrEJXASiwN/eBoc4cAcdQegsiXbmyXNBgFcAMASdur6Xu35U9FBM1CQElTiuGnLTScb/fTLbrkZ1Ine6HTrUhjqoroL6TCQDev2gpxwZVtpp3iQIg1n0ucAiokZyWSR+p4NN7VLlUSrXEGcNhVbfm3CLkiZ2WlqXwpVVcMAGbz/ovaI9yNsb/16lG7Hw4odpCRbH9uWYgEp/1iy4+NLSgpBmO1YYv5UVTFOIO8JQ="

services:
  - docker

# Only build master branch and tags of form 0.1 or 1.0.2 (all PRs will be built):
branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?$/

before_install:
  - gem install package_cloud
  - package_cloud version
  - which package_cloud

  - pip install tox-travis homebrew-pypi-poet
  - python --version
  - python2 --version
  - python3 --version

install:
  - make virtualenv

script:
  - export KUBERNAUT_VERSION=$(make version)

deploy:
  provider: script
  skip_cleanup: true
  script: ci/release.sh
  on:
    tags: true
    branch: master
