---
language: python

os:
  - linux
  - osx

python:
  - 3.6

matrix:
  include:
    - os: linux
      sudo: false

#env:
#  global:
#    - SCOUT_DISABLE=1
#    - secure: "elVwcLP2n04gNRBRfMl0+s0qiFOzZ9mqDBpyV5ylpkRdAdNQStAwLEyGs9cQsXTDwRuAPPffMPcBapwwJVoKIETcUE6RsFsK90y54w7yZKwtRLZvLv9K/XSaPsDdLiOZSDkejA5SB9M+FgseVCmV4pURRXqUxgtNoHDMbIZYF/9xKzjslTlBlwgsPprs5Nv5Pp6gxL3h+n9j3fM3gNIenSsz1un1DG0ly+kWU2KMu0ujj1yLAUVpXn3BYM+h1nuCmqUhm4/z5Bwqv3NuWyDkOmIJs72KhRZpdwDb0tn041pAXAdjCFM0vdQXbskwoN9sN5Ql4g+OamdereIUW4ZP3s5GmQ8YfJYWVizn9jmfXY2KZWjmuRebtpktAjbfpmIeriVli+IAXiIshiM++/4uSyvDHOQ8otVy38HmWD+6T0ci7ZPggHqYGLt7QGxZgKhi0f/JoVYzpWRLxpuspIT7yLJyRXvSDvlUUsOe0VfTSNH3lLzF+gTpfsskgmVnDJZ2ma/qhibwwBxOTJAh7dXt30vBqqv4shRKVzCTUSuYnUANWU24K4Rc5Tj2hQlKjaTJRri1v8LD+rkg1EhF9hj290EI7SDjuXTpmOjccyr+bSkgqHZXZynnlMcOVzixXzj7Ep3PpPEDgo4i2hk9nN8LGvNCxUOFafE+VyXWlaGov6k="

services:
  - docker

before_install:
  - python3 --version

script:
  - make binary

#deploy:
#  provider: script
#  skip_cleanup: true
#  script: ci/release.sh
#  on:
#    tags: true
#    branch: master
#    python: "3.6"
