---
language: python

matrix:
  include:
    - os: linux
      sudo: false
    - os: osx
      language: generic
      env: PYTHON=3.6.5

env:
  global:
    - SCOUT_DISABLE=1

services:
  - docker

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew install python3;
      virtualenv venv -p python3;
      source venv/bin/activate
    fi
  - python --version

install:
  - pip install pipenv
  - make init

script:
  - make binary

#deploy:
#  provider: script
#  skip_cleanup: true
#  script: ci/release.sh
#  on:
#    tags: true
#    branch: master
#    python: "3.6"
