---
matrix:
  include:
    - os: linux
      language: python
      python:
        - 3.6
      sudo: false
    - os: osx
      language: generic
      env: PYTHON=3.6.5

env:
  global:
    - SCOUT_DISABLE=1

services:
  - docker

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      pip3 install virtualenv
      virtualenv venv -p python3;
      source venv/bin/activate
    fi
  - python --version

install:
  - gcloud version || true
  - |
    if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then
      rm -rf $HOME/google-cloud-sdk;
      export CLOUDSDK_CORE_DISABLE_PROMPTS=1;
      curl https://sdk.cloud.google.com | bash;
    fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - pip install pipenv
  - make init
  - gsutil --version
  - gcloud --version

script:
  - make binary

deploy:
  - provider: script
    script: make publish
    on:
      branch: master2
#  - provider: script
#    script: make publish
#    on:
#      tags: true