---
matrix:
  include:
    - os: linux
      language: python
      python:
        - 3.6
      sudo: false
    - os: osx
      language: generic
      env: PYTHON=3.6.5

cache:
  directories:
  - "$HOME/google-cloud-sdk/"

env:
  global:
    - SCOUT_DISABLE=1

services:
  - docker

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      pip3 install virtualenv
      virtualenv venv -p python3;
      source venv/bin/activate
    fi
  - python --version

install:
  - curl https://storage.googleapis.com/pub/gsutil.tar.gz
  - tar xfz gsutil.tar.gz -C $HOME
  - export PATH=${PATH}:$HOME/gsutil
  - pip install pipenv
  - make init
  - gsutil --version

script:
  - make binary

deploy:
  - provider: script
    script: make publish
    on:
      branch: master
  - provider: script
    script: make publish
    on:
      tags: true