---
matrix:
  include:
    - os: linux
      language: python
      python:
        - 3.6
      sudo: false
    - os: osx
      osx_image: xcode6.4
      language: generic
      env: PYTHON=3.6.5

env:
  global:
    - SCOUT_DISABLE=1
    - GCLOUD_KEYFILE=datawireio-cloud-ff47e83d3663.json

services:
  - docker

before_install:
  - |
    openssl aes-256-cbc \
      -K $encrypted_be4a8a531a51_key \
      -iv $encrypted_be4a8a531a51_iv \
      -in ${GCLOUD_KEYFILE}.enc \
      -out ${GCLOUD_KEYFILE} \
      -d
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      pip3 install virtualenv
      virtualenv venv -p python3;
      source venv/bin/activate
    fi
  - python --version

install:
  - gcloud version || true
  - |
    if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then
      rm -rf $HOME/google-cloud-sdk;
      export CLOUDSDK_CORE_DISABLE_PROMPTS=1;
      curl https://sdk.cloud.google.com | bash;
    fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - pip install pipenv
  - make init
  - gcloud --version
  - gcloud auth activate-service-account --key-file ${GCLOUD_KEYFILE}

script:
  - make binary smoketest

deploy:
  - provider: script
    script: make publish
    skip_cleanup: true
    on:
      branch: master
